//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 07:46:30 PM CDT 
//


package com.kedzie.vbox.api.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IPciAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPciAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bus" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="device" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="devFunction" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPciAddress", propOrder = {
    "bus",
    "device",
    "devFunction"
})
public class IPciAddress {

    protected short bus;
    protected short device;
    protected short devFunction;

    /**
     * Gets the value of the bus property.
     * 
     */
    public short getBus() {
        return bus;
    }

    /**
     * Sets the value of the bus property.
     * 
     */
    public void setBus(short value) {
        this.bus = value;
    }

    /**
     * Gets the value of the device property.
     * 
     */
    public short getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     */
    public void setDevice(short value) {
        this.device = value;
    }

    /**
     * Gets the value of the devFunction property.
     * 
     */
    public short getDevFunction() {
        return devFunction;
    }

    /**
     * Sets the value of the devFunction property.
     * 
     */
    public void setDevFunction(short value) {
        this.devFunction = value;
    }

}
