//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 07:46:30 PM CDT 
//


package com.kedzie.vbox.api.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IPciDeviceAttachment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPciDeviceAttachment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isPhysicalDevice" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hostAddress" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="guestAddress" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPciDeviceAttachment", propOrder = {
    "name",
    "isPhysicalDevice",
    "hostAddress",
    "guestAddress"
})
public class IPciDeviceAttachment {

    @XmlElement(required = true)
    protected String name;
    protected boolean isPhysicalDevice;
    protected int hostAddress;
    protected int guestAddress;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isPhysicalDevice property.
     * 
     */
    public boolean isIsPhysicalDevice() {
        return isPhysicalDevice;
    }

    /**
     * Sets the value of the isPhysicalDevice property.
     * 
     */
    public void setIsPhysicalDevice(boolean value) {
        this.isPhysicalDevice = value;
    }

    /**
     * Gets the value of the hostAddress property.
     * 
     */
    public int getHostAddress() {
        return hostAddress;
    }

    /**
     * Sets the value of the hostAddress property.
     * 
     */
    public void setHostAddress(int value) {
        this.hostAddress = value;
    }

    /**
     * Gets the value of the guestAddress property.
     * 
     */
    public int getGuestAddress() {
        return guestAddress;
    }

    /**
     * Sets the value of the guestAddress property.
     * 
     */
    public void setGuestAddress(int value) {
        this.guestAddress = value;
    }

}
