//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 07:46:30 PM CDT 
//


package com.kedzie.vbox.api.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kedzie.vbox.api.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kedzie.vbox.api.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IAdditionsFacility }
     * 
     */
    public IAdditionsFacility createIAdditionsFacility() {
        return new IAdditionsFacility();
    }

    /**
     * Create an instance of {@link IMediumAttachment }
     * 
     */
    public IMediumAttachment createIMediumAttachment() {
        return new IMediumAttachment();
    }

    /**
     * Create an instance of {@link IGuestDirEntry }
     * 
     */
    public IGuestDirEntry createIGuestDirEntry() {
        return new IGuestDirEntry();
    }

    /**
     * Create an instance of {@link ISharedFolder }
     * 
     */
    public ISharedFolder createISharedFolder() {
        return new ISharedFolder();
    }

    /**
     * Create an instance of {@link IGuestOSType }
     * 
     */
    public IGuestOSType createIGuestOSType() {
        return new IGuestOSType();
    }

    /**
     * Create an instance of {@link IPciDeviceAttachment }
     * 
     */
    public IPciDeviceAttachment createIPciDeviceAttachment() {
        return new IPciDeviceAttachment();
    }

    /**
     * Create an instance of {@link IVRDEServerInfo }
     * 
     */
    public IVRDEServerInfo createIVRDEServerInfo() {
        return new IVRDEServerInfo();
    }

    /**
     * Create an instance of {@link IPciAddress }
     * 
     */
    public IPciAddress createIPciAddress() {
        return new IPciAddress();
    }

}
